### ISSUE TITLE
Error al poner las mismas unidades y luego insertar el valor a convertir

### ISSUE THREAD

**Issue by Jorexdev** [righelCH/QuantumConvertor#1]
Jajajaj te acabo de pillar un bug, todo un QA soy.

Le pongo de Gigabyte a Gigabyte y pongo un valor a convertir desaparecen bastantes componentes gráficos.

**Comment by righelCH** [comment]
Gracias por tu observación! He corregido el error manejando los nulos de los ítems al inicializar la app. Considera ser mi QA! xd
Fixed #1

**Comment by Jorexdev** [comment]
Jajajaj me lo apunto, estoy creando un disc con una amiga sobre programacion, si quieres que te invite avisame por whastapp :)
